import { useCallback, useState } from 'react';
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useFocusEffect, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { listPayments, listPurchases, listVendors, setPurchasesPaid } from '../../src/db/repository';
import type { Purchase, Vendor } from '../../src/types';
import { formatBRL, formatCurrencyInput, parseBRLToCents } from '../../src/services/money';
import { formatDate, monthRange, parseBRDate, todayISO } from '../../src/services/dates';
import { Button, Card, EmptyState, Field, PageHeader, Screen, SectionTitle } from '../../src/components/ui';
import { PurchaseCard } from '../../src/components/PurchaseCard';
import { colors } from '../../src/theme';

const months = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez'];
const shift = (d: Date, step: number) => new Date(d.getFullYear(), d.getMonth() + step, 1, 12);

export default function HistoryScreen() {
  const router = useRouter(); const [month, setMonth] = useState(() => new Date()), [vendors, setVendors] = useState<Vendor[]>([]), [vendorId, setVendorId] = useState('');
  const [status, setStatus] = useState<'all' | 'pending' | 'paid'>('all'), [items, setItems] = useState<Purchase[]>([]), [payments, setPayments] = useState<Array<{ id: string; vendorName: string; paymentDate: string; totalCents: number; purchaseCount: number }>>([]);
  const [selected, setSelected] = useState<string[]>([]), [payModal, setPayModal] = useState(false), [payDate, setPayDate] = useState(todayISO());
  const [showFilters, setShowFilters] = useState(false), [customPeriod, setCustomPeriod] = useState(false), [from, setFrom] = useState(formatDate(monthRange().from)), [to, setTo] = useState(formatDate(monthRange().to)), [minimum, setMinimum] = useState(''), [maximum, setMaximum] = useState('');
  const load = useCallback(() => { void (async () => {
    const range = customPeriod ? { from: parseBRDate(from), to: parseBRDate(to) } : monthRange(month), minCents = minimum ? parseBRLToCents(minimum) ?? undefined : undefined, maxCents = maximum ? parseBRLToCents(maximum) ?? undefined : undefined;
    const itemQuery = customPeriod && (!range.from || !range.to) ? Promise.resolve([] as Purchase[]) : listPurchases({ from: range.from ?? undefined, to: range.to ?? undefined, vendorId: vendorId || undefined, status: status === 'all' ? undefined : status, minCents, maxCents });
    const [allItems, sellerList, paymentRows] = await Promise.all([itemQuery, listVendors(), listPayments()]);
    setItems(allItems); setVendors(sellerList); setPayments(paymentRows); setSelected([]);
  })(); }, [month, vendorId, status, customPeriod, from, to, minimum, maximum]);
  useFocusEffect(load);
  const pendingSelected = selected.filter((id) => items.some((item) => item.id === id && item.paymentStatus === 'pending'));
  const paySelected = async () => {
    const parsedDate = parseBRDate(payDate);
    if (!parsedDate) { Alert.alert('Data inválida', 'Informe uma data no formato DD/MM/AAAA.'); return; }
    try { await setPurchasesPaid(pendingSelected, parsedDate); setPayModal(false); setSelected([]); load(); }
    catch { Alert.alert('Não foi possível salvar', 'Tente novamente.'); }
  };
  return <Screen>
    <PageHeader title="Histórico" subtitle="Todas as compras em um só lugar." action={<Pressable onPress={() => router.push('/purchase/new')} style={styles.iconButton}><Ionicons name="add" size={24} color="#fff" /></Pressable>} />
    <Card style={styles.monthCard}><Pressable onPress={() => { setCustomPeriod(false); setMonth(shift(month, -1)); }} style={styles.arrow}><Ionicons name="chevron-back" color={colors.green} size={20} /></Pressable><View style={{ alignItems: 'center' }}><Text style={styles.monthLabel}>{customPeriod ? 'PERÍODO PERSONALIZADO' : 'MÊS DAS COMPRAS'}</Text><Text style={styles.month}>{customPeriod ? `${formatDate(from)} – ${formatDate(to)}` : `${months[month.getMonth()]} ${month.getFullYear()}`}</Text></View><Pressable onPress={() => { setCustomPeriod(false); setMonth(shift(month, 1)); }} style={styles.arrow}><Ionicons name="chevron-forward" color={colors.green} size={20} /></Pressable></Card>
    <Pressable onPress={() => setShowFilters((v) => !v)} style={styles.filterToggle}><Ionicons name="options-outline" size={18} color={colors.green} /><Text style={styles.filterToggleText}>{showFilters ? 'Ocultar filtros' : 'Mais filtros'}</Text><Ionicons name={showFilters ? 'chevron-up' : 'chevron-down'} size={16} color={colors.green} /></Pressable>
    {showFilters ? <Card style={{ gap: 12 }}><Pressable onPress={() => setCustomPeriod((v) => !v)} style={styles.customToggle}><Ionicons name={customPeriod ? 'checkbox' : 'square-outline'} size={20} color={colors.green} /><Text style={styles.customText}>Usar período personalizado</Text></Pressable>{customPeriod ? <View style={styles.dateFields}><Field label="De (DD/MM/AAAA)" value={from} onChangeText={setFrom} placeholder="01/01/2026" keyboardType="numbers-and-punctuation" /><Field label="Até (DD/MM/AAAA)" value={to} onChangeText={setTo} placeholder="31/01/2026" keyboardType="numbers-and-punctuation" /></View> : null}<View style={styles.dateFields}><Field label="Valor mínimo" value={minimum} onChangeText={(v) => setMinimum(formatCurrencyInput(v))} placeholder="0,00" keyboardType="decimal-pad" /><Field label="Valor máximo" value={maximum} onChangeText={(v) => setMaximum(formatCurrencyInput(v))} placeholder="0,00" keyboardType="decimal-pad" /></View></Card> : null}
    <View style={styles.filterRow}>{(['all', 'pending', 'paid'] as const).map((value) => <Pressable key={value} onPress={() => setStatus(value)} style={[styles.pill, status === value && styles.pillActive]}><Text style={[styles.pillText, status === value && styles.pillTextActive]}>{value === 'all' ? 'Todas' : value === 'pending' ? 'Pendentes' : 'Pagas'}</Text></Pressable>)}</View>
    <View style={styles.vendorScroll}><Pressable onPress={() => setVendorId('')} style={[styles.vendorPill, !vendorId && styles.vendorSelected]}><Text style={[styles.vendorText, !vendorId && styles.vendorTextActive]}>Todos</Text></Pressable>{vendors.map((v) => <Pressable key={v.id} onPress={() => setVendorId(v.id === vendorId ? '' : v.id)} style={[styles.vendorPill, vendorId === v.id && styles.vendorSelected]}><Text style={[styles.vendorText, vendorId === v.id && styles.vendorTextActive]}>{v.name}</Text></Pressable>)}</View>
    {pendingSelected.length > 0 ? <Button title={`Marcar ${pendingSelected.length} como paga${pendingSelected.length > 1 ? 's' : ''}`} onPress={() => { setPayDate(formatDate(todayISO())); setPayModal(true); }} icon={<Ionicons name="checkmark-circle-outline" size={19} color="#fff" />} /> : null}
    {items.some((item) => item.paymentStatus === 'pending') ? <Pressable onPress={() => { const ids = items.filter((item) => item.paymentStatus === 'pending').map((item) => item.id); setSelected(pendingSelected.length === ids.length ? [] : ids); }} style={styles.selectAll}><Ionicons name={pendingSelected.length === items.filter((item) => item.paymentStatus === 'pending').length ? 'checkbox' : 'square-outline'} size={19} color={colors.green} /><Text style={styles.selectAllText}>{pendingSelected.length === items.filter((item) => item.paymentStatus === 'pending').length ? 'Desmarcar pendentes' : 'Selecionar todas as pendentes'}</Text></Pressable> : null}
    <SectionTitle>{items.length} {items.length === 1 ? 'compra' : 'compras'}</SectionTitle>
    {items.length ? <View style={{ gap: 9 }}>{items.map((item) => <PurchaseCard key={item.id} item={item} onPress={() => router.push({ pathname: '/purchase/[id]', params: { id: item.id } })} selected={selected.includes(item.id)} onToggle={item.paymentStatus === 'pending' ? () => setSelected((previous) => previous.includes(item.id) ? previous.filter((id) => id !== item.id) : [...previous, item.id]) : undefined} />)}</View> : <Card><EmptyState title="Nenhuma compra por aqui" detail="Ajuste os filtros ou registre um lanche novo." icon={<Ionicons name="receipt-outline" size={30} color={colors.green} />} /></Card>}
    <View style={{ gap: 10 }}><SectionTitle>Histórico de pagamentos</SectionTitle>{payments.length ? payments.slice(0, 12).map((payment) => <Card key={payment.id} style={styles.paymentRow}><View style={{ flex: 1 }}><Text style={styles.paymentVendor}>{payment.vendorName}</Text><Text style={styles.paymentMeta}>{formatDate(payment.paymentDate)} · {payment.purchaseCount} {payment.purchaseCount === 1 ? 'compra' : 'compras'}</Text></View><Text style={styles.paymentTotal}>{formatBRL(payment.totalCents)}</Text></Card>) : <Card><Text style={styles.noPayments}>Pagamentos confirmados aparecerão aqui.</Text></Card>}</View>
    <Modal visible={payModal} transparent animationType="fade" onRequestClose={() => setPayModal(false)}><View style={styles.modalShade}><View style={styles.modal}><Text style={styles.modalTitle}>Confirmar pagamento</Text><Text style={styles.modalCopy}>Data em que essas compras foram pagas.</Text><Text style={styles.label}>Data do pagamento (DD/MM/AAAA)</Text><TextInput value={payDate} onChangeText={setPayDate} placeholder="14/09/2026" keyboardType="numbers-and-punctuation" style={styles.dateInput} /><View style={styles.modalButtons}><Button title="Voltar" variant="secondary" onPress={() => setPayModal(false)} /><Button title="Confirmar" onPress={() => void paySelected()} /></View></View></View></Modal>
  </Screen>;
}

const styles = StyleSheet.create({ iconButton: { height: 44, width: 44, borderRadius: 15, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' }, monthCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 11 }, arrow: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.greenLight, alignItems: 'center', justifyContent: 'center' }, monthLabel: { color: colors.muted, fontSize: 9, letterSpacing: 1, fontWeight: '800' }, month: { color: colors.ink, fontSize: 16, textTransform: 'capitalize', fontWeight: '800', marginTop: 3 }, filterToggle: { minHeight: 42, flexDirection: 'row', alignItems: 'center', gap: 7 }, filterToggleText: { color: colors.green, fontSize: 13, fontWeight: '800' }, customToggle: { flexDirection: 'row', alignItems: 'center', gap: 8 }, customText: { color: colors.ink, fontWeight: '700', fontSize: 13 }, dateFields: { flexDirection: 'row', gap: 10 }, selectAll: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 2 }, selectAllText: { color: colors.green, fontWeight: '700', fontSize: 12 }, filterRow: { flexDirection: 'row', gap: 8 }, pill: { backgroundColor: '#EEF0ED', paddingHorizontal: 15, paddingVertical: 9, borderRadius: 99 }, pillActive: { backgroundColor: colors.green }, pillText: { color: colors.muted, fontSize: 12, fontWeight: '700' }, pillTextActive: { color: '#fff' }, vendorScroll: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, vendorPill: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 99, backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1 }, vendorSelected: { backgroundColor: colors.greenLight, borderColor: colors.green }, vendorText: { color: colors.muted, fontSize: 11, fontWeight: '600' }, vendorTextActive: { color: colors.green }, paymentRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 14 }, paymentVendor: { color: colors.ink, fontWeight: '800', fontSize: 13 }, paymentMeta: { color: colors.muted, fontSize: 11, marginTop: 4 }, paymentTotal: { color: colors.green, fontWeight: '800' }, noPayments: { color: colors.muted, fontSize: 12 }, modalShade: { flex: 1, justifyContent: 'center', padding: 24, backgroundColor: '#15231FCC' }, modal: { padding: 20, borderRadius: 22, backgroundColor: '#fff', gap: 12 }, modalTitle: { fontSize: 20, color: colors.ink, fontWeight: '800' }, modalCopy: { color: colors.muted, lineHeight: 20 }, label: { fontSize: 12, color: colors.ink, fontWeight: '700', marginTop: 8 }, dateInput: { borderRadius: 12, borderColor: colors.line, borderWidth: 1, paddingHorizontal: 13, height: 48, color: colors.ink }, modalButtons: { flexDirection: 'row', gap: 9, justifyContent: 'flex-end', marginTop: 5 } });
